### ISSUE TITLE
[PHP 8] Core language tests use outdated WordPress versions

### ISSUE THREAD

**Issue by TimothyBJacobs** [wp-cli/language-command#103]
Similar to https://github.com/wp-cli/core-command/issues/172, the language tests use outdated versions of WordPress that aren't compatible with PHP 8.

```
$ wp language core install nl_NL

    PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-language-core.feature.301-5fac6176cd9c30.48904367/wp-includes/load.php:610
    Stack trace:
    #0 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-settings-cli.php(339): wp_magic_quotes()
    #1 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1253): require('/Users/timothyb...')
    #2 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1172): WP_CLI\Runner->load_wordpress()
    #3 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #4 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #5 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
    #6 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/boot-fs.php(17): require_once('/Users/timothyb...')
    #7 {main}
      thrown in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-language-core.feature.301-5fac6176cd9c30.48904367/wp-includes/load.php on line 610
    Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-language-core.feature.301-5fac6176cd9c30.48904367/wp-includes/load.php:610
    Stack trace:
    #0 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-settings-cli.php(339): wp_magic_quotes()
    #1 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1253): require('/Users/timothyb...')
    #2 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1172): WP_CLI\Runner->load_wordpress()
    #3 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #4 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #5 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
    #6 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/boot-fs.php(17): require_once('/Users/timothyb...')
    #7 {main}
      thrown in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-language-core.feature.301-5fac6176cd9c30.48904367/wp-includes/load.php on line 610
    cwd: /var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-language-core.feature.301-5fac6176cd9c30.48904367/
    run time: 0.24238705635071
    exit status: 255
    In step `When I run `wp language core install nl_NL`'.               # /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli-tests/features/steps/when.php:29
    From scenario `Ensure correct language is installed for WP version'. # features/language-core.feature:301
    Of feature `Manage translation files for a WordPress install'.
```

**Comment by danielbachhuber** [comment]
Probably no longer an issue https://github.com/wp-cli/core-command/issues/172#issuecomment-1435315801
